name: Auto Commit

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to push changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes (Optional)
        run: |
          echo "Auto update at $(date)" >> auto_update.txt

      - name: Configure Git
        run: |
          git config --global user.email "devathasakethkumar@gmail.com"
          git config --global user.name "sakethkumardevatha"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Auto commit at $(date)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
